### ISSUE TITLE
AR Blog: Display text right-aligned

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#201]
We have noticed that in Arabic Blog entries the text is displayed left-aligned instead of right-aligned. Interestingly, the AR Wikis are displayed correctly. The same bug exists for the position of the Table of Contents. The task would be to make the Blog display arabic entries the same way as the Wiki does.

For comparison, here a AR Wiki:
![grafik](https://user-images.githubusercontent.com/96528343/235642089-94f9d3ce-79ac-4af7-a201-09f463b81d62.png)

And an AR Blog entry: 
![grafik](https://user-images.githubusercontent.com/96528343/235641971-f71545bd-2dc9-403e-99e8-a1b6662abcc4.png)

**Comment by benjaoming** [comment]
It seems some posts have been imported correctly but into the wrong language. So the Arabic blog post is incorrectly nested under the English Blog section.

I moved all the Arabic blog posts like this:

Step 1: Edit the post

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/a83e85fc-d447-4e8d-816d-e34352776ed4)

Step 2: Move it

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/799cc3b0-f3d1-4ac4-9137-2f9a2b1ec37c)

Step 3: Choose the Arabic "Blog" section

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/0426eaca-9ecb-43f9-a437-4a17fa321b0d)

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/454aa0c1-578d-474f-bdc6-94c2e66eada1)

Step 4: Choose Blog after activating Arabic

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/b0310a52-988c-44ec-bc07-15dd9e1616c1)

Step 5: Confirm

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/ea6dc0eb-273d-4872-8ce1-27be55e58665)


## Important?

I think the old French and German blog posts have the same issue, the language doesn't _actually_ change on the website because they are nested under the English Blog index... but it doesn't seem so critical.
