### ISSUE TITLE
German site: translations missing

### ISSUE THREAD

**Issue by teabag12** [migcontrol/django-migcontrol#250]
German site: under 'Material', translate all of the table's column names to German, maybe change the column 'Media' to something more fitting

**Comment by benjaoming** [comment]
This can be fixed in this file:

https://github.com/migcontrol/django-migcontrol/blob/main/locale/de/LC_MESSAGES/django.po

Since the file is machine-read the syntax is important.

Everything with `msgstr ""` or `fuzzy` is untranslated. The important ones have a comment that indicates that it's from a `.html` file, and the ones from a `model.py` are less important.

**Comment by benjaoming** [comment]
If you work on this, please make sure to open a PR, as the .po file will be validated in the build process :+1:
