### ISSUE TITLE
BLOG: Missing Pictures

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#72]
In many of the imported blog post's the pictures are missing.

Compare this on the new site: ![grafik](https://user-images.githubusercontent.com/96528343/167389070-e5dc4775-6925-44b3-a537-af46891c63ee.png)
with the old: 
![grafik](https://user-images.githubusercontent.com/96528343/167389220-2b1bd2ed-cb5f-481f-b659-3493c58f1707.png)

This seems to be the issue most of the times, but not always. On the newest three blog posts, for example, the pictures are displayed normally but in the older posts they are not.

**Comment by benjaoming** [comment]
The issue was indeed that we had imported a new version posts -- but the media xml imported was old.

Blog post from example has an image now: https://migcontrol.overtag.dk/en/blog/all-sails-set-for-more-of-the-same-leaked-eu-document-on-the-operational-coordination-mechanism-for-the-external-dimension-of-migration/
